export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";
export const GET_HEADLINES = "GET_HEADLINES";
export const UPDATE_HEADLINES = "UPDATE_HEADLINES"
export const SEND_SEARCH = "SEND_SEARCH";
export const GET_SENTIMENT = "GET_SENTIMENT";