export const GET_HEADLINES = "GET_HEADLINES";
export const UPDATE_HEADLINES = "UPDATE_HEADLINES";
export const UPDATE_CHART = "UPDATE_CHART";
export const INITIATE_CHART ="INITIATE_CHART";
export const HEADLINES_FAILURE = "HEADLINES_FAILURE";
export const REMOVE_ERROR = "REMOVE_ERROR";